spring.application.name=data-classification

spring.profiles.active=dev

server.servlet.context-path=/api

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.datasource.driver-class-name=org.postgresql.Driver

sem-rush.url=https://api.semrush.com/
sem-rush.api-key=PLACE_API_KEY_HERE
sem-rush.metrics=Or,Ot
sem-rush.type=rank
sem-rush.database=us

browser.headless=true

spring.ai.ollama.init.pull-model-strategy=when_missing
spring.ai.ollama.init.max-retries=3
spring.ai.ollama.init.timeout=10m
spring.ai.ollama.embedding.options.keep-alive=30m

embedding.treshold=0.52
