server.port=8080
server.host=localhost

spring.datasource.url=jdbc:postgresql://localhost:8685/data_classification_db
spring.datasource.username=data_classification_user
spring.datasource.password=supersecretpassword

spring.ai.ollama.base-url=http://localhost:11434