server.port=8080
server.host=localhost

spring.datasource.url=jdbc:postgresql://194.163.164.118:8685/data_classification_db
spring.datasource.username=data_classification_user
spring.datasource.password=supersecretpassword

spring.ai.ollama.base-url=http://194.163.164.118:11434

nst-browser.host=194.163.164.118
nst-browser.port=7478
nst-browser.url=http://194.163.164.118:${nst-browser.port}/api/v2
nst-browser.headless=true