spring.application.name=data-classification

spring.profiles.active=prod

server.servlet.context-path=/api

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.datasource.driver-class-name=org.postgresql.Driver

sem-rush.url=https://api.semrush.com/
sem-rush.api-key=PLACE_API_KEY_HERE
sem-rush.metrics=Or,Ot
sem-rush.type=rank
sem-rush.database=us

spring.ai.ollama.init.pull-model-strategy=when_missing
spring.ai.ollama.init.max-retries=3
spring.ai.ollama.init.timeout=10m
spring.ai.ollama.embedding.options.keep-alive=30m

embedding.treshold=0.52

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=melnukoleksandr2023@gmail.com
spring.mail.password=bdygrhmgwlvlbkwr
spring.mail.to=info@petzoo.com.au
spring.mail.from=no-reply@gmail.com
spring.mail.reply-to=no-reply
spring.mail.properties.protocol=smtp
spring.mail.properties.auth=true
spring.mail.properties.starttls.enabled=true

nst-browser.api-key=${NST_TOKEN:2b95d0f1-e96c-4e65-9e7d-d2b80b9e4770}
nst-browser.group-id=980aad55-f13c-4ca6-a256-0537b3dbf710