server.port=9194
server.host=194.163.164.118

spring.datasource.url=jdbc:postgresql://postgres-data-classification:5432/data_classification_db
spring.datasource.username=data_classification_user
spring.datasource.password=supersecretpassword

spring.ai.ollama.base-url=http://ollama-data-classification:11434

nst-browser.host=nstbrowserless-data-classification
nst-browser.port=8848
nst-browser.url=http://${nst-browser.host}:${nst-browser.port}/api/v2
nst-browser.headless=false