server.port=8786
server.host=194.163.164.118

spring.datasource.url=jdbc:postgresql://postgres_data_classification:5432/data_classification_db
spring.datasource.username=data_classification_user
spring.datasource.password=supersecretpassword
