version: "3.3"

networks:
  data-classification-net:

services:
  application:
    container_name: app-data-classification
    build:
      context: ..
      dockerfile: ./Dockerfile
    restart: unless-stopped
    ports:
      - "${API_PORT}:3344"
    networks:
      - data-classification-net
    depends_on:
      - ollama
      - postgres-data-classification

  ollama:
    image: ollama/ollama:latest
    container_name: ollama-data-classification
    restart: unless-stopped
    ports:
      - "${OLLAMA_PORT}:11434"
    networks:
      - data-classification-net
    volumes:
      - data_classification_volume:/root/.ollama

  postgres-data-classification:
    image: postgres:16
    restart: unless-stopped
    networks:
      - data-classification-net
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - data_classification_volume:/var/lib/postgresql/data

volumes:
  data_classification_volume:
