version: "3.3"

networks:
  data-classification-net:

services:
  app-data-classification:
    build:
      context: ..
      dockerfile: ./Dockerfile
    restart: unless-stopped
    ports:
      - "${API_PORT}:${API_PORT}"
    networks:
      - data-classification-net
    depends_on:
      - ollama-data-classification
      - postgres-data-classification

  ollama-data-classification:
    image: ollama/ollama:latest
    restart: unless-stopped
    ports:
      - "${OLLAMA_PORT}:11434"
    networks:
      - data-classification-net
    volumes:
      - data_classification_volume:/root/.ollama

  postgres-data-classification:
    image: postgres:16
    restart: unless-stopped
    networks:
      - data-classification-net
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - data_classification_volume:/var/lib/postgresql/data

  nstbrowserless-data-classification:
    image: nstbrowser/browserless:143-202512151200.v1
    restart: unless-stopped
    networks:
      - data-classification-net
    environment:
      TZ: America/New_York
      LANG: en_US.UTF-8
      LANGUAGE: en_US:en
      LC_ALL: en_US.UTF-8
      TOKEN: ${NST_TOKEN}
      VNC_PORT: ${VNC_PORT}
      VNC_PASSWORD: ${VNC_PASSWORD}
    ports:
      - "${NST_PORT}:8848"
      - "${VNC_PORT}:6900"

volumes:
  data_classification_volume:
